on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: "Login to Docker hub"
        run: docker login --username ${{ secrets.DOCKER_USERNAME }}  --password ${{ secrets.DOCKER_PASS_TOKEN }} 

      - name: "Build Docker image"
        run: docker docker build -t ${{ secrets.DOCKER_USERNAME }}/my-html-app2 .

      - name: "Push to Dockerhub"
        run: docker docker push ${{ secrets.DOCKER_USERNAME }}/my-html-app2





